# Generated by Django 4.0.3 on 2022-04-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rec_Word_In_English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_english', models.CharField(max_length=255)),
                ('word_in_twi', models.CharField(max_length=255)),
                ('word_meaning', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rec_Word_In_Twi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_in_twi', models.CharField(max_length=255)),
                ('word_in_english', models.CharField(max_length=255)),
                ('word_meaning', models.CharField(max_length=255)),
            ],
        ),
    ]
