# Generated by Django 4.0.3 on 2022-04-10 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_rec_word_in_english_rec_word_in_twi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rec_Word_In_English',
            new_name='Add_English_Word',
        ),
        migrations.RenameModel(
            old_name='Rec_Word_In_Twi',
            new_name='Add_Twi_Word',
        ),
    ]
